---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: gic-98083
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: registry.deti/gic-98083/app:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: gic-98083
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-gic-98083-k3s
  namespace: gic-98083
  annotations:
    spec.ingressClassName: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: app-gic-98083.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port: 
              number: 80
