---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  namespace: gic-98083
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-v2
  template:
    metadata:
      labels:
        app: app-v2
    spec:
      containers:
      - name: app
        image: registry.deti/gic-98083/app-v2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-v2
  namespace: gic-98083
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app-v2

