---
apiVersion: apps/v1
#kind: DaemonSet
#kind: ReplicaSet
kind: Deployment
metadata:
  name: app-v1
  namespace: gic-98083
spec:
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
        course: gic
        year: "2024"
    spec:
      containers:
      - name: app
        image: registry.deti/gic-98083/app:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
